function [ probs ] = ising_probabilities( coeffs, state_mat )
%Generates probabilities for an ising model with parameters alpha 
%(Nx1 vector of  fields) and beta (NxN matrix of couplings).
%INPUTS:
%   alpha: [N x 1 vector] of biases / fields (-1 to 1)
%   beta: [N x N matrix] of couplings
%   state_mat: [(N+(N^2-N)/2) x 2^N vector where each row represents a state and
%       the numbers given are [x1 x2 x3... x11 x12 x13 ... x21 x22 ... xNN]
%       This is generated by the function generate_state_mat
%OUTPUTS:
%   probs: [2^N x 1 vector] of the probability of each state

probs = exp(state_mat' * coeffs'); %get probabilities (unnormalized)

probs = probs ./ sum(probs); %normalize probabilities

end

